'use client';

import { useState, useTransition } from 'react';
import { getPersonalizedMessage } from '@/app/actions';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { MessageSquareHeart, Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

export default function PersonalizedMessage() {
  const [message, setMessage] = useState('');
  const [isPending, startTransition] = useTransition();
  const { toast } = useToast();

  const handleGenerate = async () => {
    setMessage('');
    startTransition(async () => {
      try {
        const result = await getPersonalizedMessage();
        if (result) {
          setMessage(result);
        } else {
          throw new Error('No message generated');
        }
      } catch (error) {
        console.error(error);
        toast({
          variant: 'destructive',
          title: 'Oh no! Something went wrong.',
          description:
            'There was a problem generating your message. Please try again.',
        });
      }
    });
  };

  const running = isPending;

  return (
    <section>
      <h2 className="font-headline text-3xl md:text-4xl text-center mb-8">
        A Message Just For You
      </h2>
      <Card className="max-w-2xl mx-auto bg-card/80 backdrop-blur-sm shadow-lg">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 font-headline text-2xl">
            <MessageSquareHeart /> From the Heart
          </CardTitle>
          <CardDescription className="font-body">
            A special message generated by AI, inspired by heartfelt feelings.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {message ? (
            <p className="text-lg font-body whitespace-pre-wrap leading-relaxed">
              {message}
            </p>
          ) : (
            <div className="text-center text-muted-foreground p-8">
              <p>
                Click the button to reveal a unique birthday message written
                just for you.
              </p>
            </div>
          )}
          <div className="flex justify-center mt-6">
            <Button onClick={handleGenerate} disabled={running} size="lg">
              {running ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating...
                </>
              ) : (
                '✨ Reveal Your Message'
              )}
            </Button>
          </div>
        </CardContent>
      </Card>
    </section>
  );
}
